### ISSUE TITLE
NullPointerException on Unload

### ISSUE THREAD

**Issue by orbisvicis** [tukkek/javelin#235]
When unloading 3 (rock?) resources into a town:

```
java.lang.NullPointerException
	at javelin.view.mappanel.Tile.drawcover(Tile.java:68)
	at javelin.view.mappanel.world.WorldTile.paint(WorldTile.java:42)
	at javelin.view.mappanel.Tile.repaint(Tile.java:56)
	at javelin.view.mappanel.world.WorldPanel.refresh(WorldPanel.java:71)
	at javelin.Javelin.redraw(Javelin.java:532)
	at javelin.model.world.location.town.labor.Labor.ready(Labor.java:131)
	at javelin.model.world.location.town.labor.Labor.work(Labor.java:120)
	at javelin.model.world.location.town.governor.Governor.work(Governor.java:79)
	at javelin.view.screen.town.TownScreen.select(TownScreen.java:77)
	at javelin.view.screen.town.SelectScreen.select(SelectScreen.java:149)
	at javelin.view.screen.town.TownScreen.select(TownScreen.java:178)
	at javelin.view.screen.town.SelectScreen.processinput(SelectScreen.java:120)
	at javelin.view.screen.town.SelectScreen.show(SelectScreen.java:77)
	at javelin.view.screen.town.TownScreen.<init>(TownScreen.java:48)
	at javelin.model.world.location.town.Town.interact(Town.java:231)
	at javelin.view.screen.WorldScreen.react(WorldScreen.java:385)
	at javelin.controller.action.world.WorldMove.move(WorldMove.java:97)
	at javelin.controller.action.world.WorldMove.perform(WorldMove.java:87)
	at javelin.view.screen.WorldScreen.perform(WorldScreen.java:161)
	at javelin.view.screen.WorldScreen.move(WorldScreen.java:141)
	at javelin.view.screen.WorldScreen.turn(WorldScreen.java:179)
	at javelin.JavelinApp.loop(JavelinApp.java:117)
	at javelin.JavelinApp.run(JavelinApp.java:102)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

1.7 beta 16 with openjdk 11.0.1.

**Comment by tukkek** [comment]
Sorry it took me this long to reply but only today I have a new version out. The entire Resource system has been redesigned so I'm closing this issue as it's no longer relevant.

I have come across this issue several times though and I believe it's fixed (it was trying to redraw the game World while the World Screen wasn't showing, which made the game confused, hence the NPE).

If you're interested in the new beta, [check it out here](https://github.com/tukkek/javelin/releases/tag/1.7b17) (may be buggy as well). Again thank you for your contribution and sorry I didn't address it sooner!
