### ISSUE TITLE
Game Does Not Start

### ISSUE THREAD

**Issue by cjduncana** [tukkek/javelin#3]
I just recently downloaded V1.1 and I start it, but only see a black screen. The menu shows the game title "Javelin", but the content of the program is just a black screen.

This is the output from java:

```
java.io.FileNotFoundException: monsters.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at javelin.Javelin.<clinit>(Javelin.java:94)
Exception in thread "Thread-3" java.lang.RuntimeException: java.io.FileNotFoundException: README.txt (No such file or directory)
	at javelin.JavelinApp.initialize(JavelinApp.java:122)
	at javelin.JavelinApp.run(JavelinApp.java:72)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: README.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at javelin.JavelinApp.initialize(JavelinApp.java:113)
	... 2 more
```

It seems that certain files are not found.

**Comment by cjduncana** [comment]
I have the same problem with V1.0

**Comment by tukkek** [comment]
Hello and thank you for your interest in Javelin! Are you running the game from command-line or by clicking on the files with your mouse? If you are running from command-line please make sure that you are in the same directory as the file "javelin.jar" and "monsters.xml" is in.

I'm assuming you downloaded a zipped-file release and unpacked all of it's contents, which would result in a "Javelin" directory being created.

**Comment by tukkek** [comment]
Also, if you're using Windows please try double-clicking "start.bat" and see if it the game opens properly that way.

**Comment by cjduncana** [comment]
I am using Ubuntu. If I run the jar from the folder GUI or through CLI outside of the directory, then it does not work, but if I run it from the CLI inside the directory it works fine. Does it have to be this way?

**Comment by tukkek** [comment]
Yes, for now. Ideally we should have a .deb package which you could install through apt but it's not something I will have time to do any time soon now. This way the package would install menu entries and so on and this wouldn't be a problem.

I am developing the game on Debian and here if I simply click on the javelin.jar the game opens up fine so it seems this is only a problem on some (older?) systems. 

Do send me a mail/post on reddit to tell how you like the game (or hate it) if you have the time :) Happy leveling up and looting!
