### ISSUE TITLE
java.lang.NoSuchMethodError when starting game

### ISSUE THREAD

**Issue by rndmh3ro** [tukkek/javelin#7]
```
basti ~/Downloads/javelin $  java -jar javelin.jar 
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.Class.getTypeName()Ljava/lang/String;
	at javelin.controller.challenge.factor.quality.QualitiesFactor.calculate(QualitiesFactor.java:22)
	at javelin.controller.challenge.ChallengeRatingCalculator.calculaterawcr(ChallengeRatingCalculator.java:109)
	at javelin.controller.challenge.ChallengeRatingCalculator.calculateCr(ChallengeRatingCalculator.java:83)
	at javelin.controller.db.reader.MonsterReader.registermonster(MonsterReader.java:512)
	at javelin.controller.db.reader.MonsterReader.endElement(MonsterReader.java:489)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1783)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2970)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at javelin.Javelin.<clinit>(Javelin.java:99)
```

```
basti ~/Downloads/javelin $  java -version
java version "1.7.0_99"
OpenJDK Runtime Environment (IcedTea 2.6.5) (Arch Linux build 7.u99_2.6.5-1-x86_64)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```
```
basti ~/Downloads/javelin $  uname -a
Linux archlinux 4.5.1-1-ARCH #1 SMP PREEMPT Thu Apr 14 19:19:32 CEST 2016 x86_64 GNU/Linux
```

**Comment by tukkek** [comment]
Hello there pal, thank you for taking an interest in Javelin! I'm afraid you have to upgrade to Java 8 as the website says. Let me know how it goes :)

**Comment by rndmh3ro** [comment]
Sorry for not reading! With Java 8 it works, thanks!

**Comment by tukkek** [comment]
Sure, no problem, it's the thought that counts :) I'm working on a new bugfix release to solve a few outstanding issues that have been reported to me and I'll try to put in a Java version warning if the user is not on Java 8 since this is something that has been reported to me a few times already.

So stay tuned at our website or here if you want to update to the newer version which should be more stable! Hopefully it will be out in a day or two with any luck!

Let me know if you happen upon any more trouble!
